import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Navbar";
import Footer from "./components/footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "BLOGGERS- create your blogs",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
      <Header></Header>{children}
      <Footer></Footer></body>
    </html>
  );
}
